name: 🚀 Automated Deployment

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
      - name: 📦 Package data
        run: |
          mkdir upload
          cp -r Amnesia/Config upload/
          cp -r LatestReleaseBuild/* upload/
          cp ModInfo.xml upload/
          cp README.md upload/
          cp LICENSE upload/
          cp CHANGELOG.md upload/
      - name: ✈ Upload files
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "./upload/"
          remoteDir: "./sdtd/bin/Mods/${{ github.event.repository.name }}"
          options: "--delete --asci -x .github/"
